#!/usr/bin/env php
<?php
$tests = [
    [
        'command' => 'php-validate',
        'description' => 'PHP Coding standards',
        'enable_php' => true,
        'enable_node' => false,
        'enable_artifacts' => false,
    ],
    [
        'command' => 'php-analysis',
        'description' => 'PHP Code analysis',
        'enable_php' => true,
        'enable_node' => false,
        'enable_artifacts' => true,
    ],
    [
        'command' => 'php-test',
        'description' => 'PHP Tests',
        'enable_php' => true,
        'enable_node' => false,
        'enable_artifacts' => true,
    ],
];
$phpVersions = ['7.3', '7.4', '8.0', '8.1'];
$result = [];
foreach ($phpVersions as $phpVersion) {
    foreach ($tests as $test) {
        $test['php_version'] = $phpVersion;
        $test['description'] = $test['description'] . ' (' . $phpVersion . ')';
        $result[] = $test;
    }
}
echo json_encode($result);
