name: Run from makefile
on: ['push']

jobs:
    provide_makefile_commands:
        name: Parse makefile to extract jobs I can do
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.0
            -
                id: output_data
                run: echo "::set-output name=matrix::$(.github/extract-makefile)"
        outputs:
            matrix: ${{ steps.output_data.outputs.matrix }}

    run_makefile_commands:
        needs: provide_makefile_commands
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                data: ${{ fromJson(needs.provide_makefile_commands.outputs.matrix) }}
        name: ${{ matrix.data.description }}
        steps:
            - uses: actions/checkout@v2

            -   name: Initialize the database
                run: |
                    sudo systemctl start mysql
                    mysql --user="root" --password="root" -e "CREATE DATABASE test_db character set UTF8mb4 collate utf8mb4_bin;"
                    mysql --user="root" --password="root" -e "CREATE USER IF NOT EXISTS 'tester'@'%' IDENTIFIED WITH mysql_native_password BY 'tester'; GRANT ALL PRIVILEGES ON test_db.* TO 'tester'@'%'";

            - name: Setup PHP and tools
              uses: shivammathur/setup-php@master
              if: ${{ matrix.data.enable_php }}
              with:
                  php-version: ${{ matrix.data.php_version }}
                  extensions: bz2, bcmath, curl, exif, gd, imagick, imap, intl, mysqli, pcntl, pcov, pdo_mysql, soap, xmlrpc, xsl, zip, iconv, pdo
                  tools: composer:v2
                  coverage: pcov
              env:
                  COMPOSER_TOKEN: ${{ secrets.TOKEN_GITHUB }}
            - uses: actions/setup-node@master
              if: ${{ matrix.data.enable_node }}
              with:
                  node-version: '14.x'

            - name: Install Composer dependencies
              if: ${{ matrix.data.enable_php }}
              run: composer install

            - name: Run make ci-init if available
              run: make ci-init || true

            - name: Run make command
              run: make ${{ matrix.data.command }}
